---
title: "DeepCombat"
output: html_document
---

# Preprocessing
```{r}
source("./code/load_packages.R")
set.seed(20)
raw <- as.matrix(read.csv("./data/raw.csv", header = F))
covariates <- read.csv("./data/covariates.csv", stringsAsFactors = T)
covariates$X.1 <- covariates$X.1 + 1
final_visits_covariates <- covariates %>% group_by(subid) %>% filter(VISIT == max(VISIT))
final_visits_covariates <- final_visits_covariates#[sample(663, 10), ]
final_visits_raw <- raw[final_visits_covariates$X.1, ]


#raw <- raw[covariates$Manufacturer != "Philips Medical Systems", ]
#covariates <- covariates[covariates$Manufacturer != "Philips Medical Systems", ]

input_list <- make_input_list(final_visits_raw, final_visits_covariates, data_opts = "raw")

adni_ct <- adni_ct_dataset(input_list$input_list, data_type = "all", 
                           insert_new_batch = TRUE, 
                           new_batch = matrix(0.5, nrow = nrow(input_list$input_list$data),
                                              ncol = 1))
adni_all_dl <- dataloader(adni_ct, batch_size = 64, shuffle = TRUE)
```

# Optimal DeepCombat
```{r}
n_latent_dim <- 16
deepcombat_model <- vanilla_vae(feature_dim = 62, latent_dim = n_latent_dim,
                                n_hidden = 3, n_batch = 1, n_covariate = 4,
                                inject_decoder = TRUE, inject_last = FALSE, deep_inject = FALSE,
                                rescale = FALSE, rescale_n_batch = NULL)
resid_optim <- optim_adam(deepcombat_model$parameters, lr = 0.01, weight_decay = 0)

trained_model <- train_nn_annealer(train_epochs = c(5, 30, 5),
                                   anneal_rate = 5,
                                   beta_weights = c(.1, 0, 0),
                                   torch_dl = adni_all_dl,
                                   torch_model = deepcombat_model,
                                   torch_optim = resid_optim,
                                   batch_weights = c(1, 1),
                                   pairwise_type = "none")
deepcombat_model <- trained_model$model

deepcombat_model$eval()
deepcombat_optimal <- deepcombat_model$encode_decode(adni_ct,
                                                     attr(input_list$input_list$data,
                                                          which = "scaled:center") + input_list$mean,
                                                     attr(input_list$input_list$data,
                                                          which = "scaled:scale"),
                                                     correct = c("combat", "combat"),
                                                     mean_only = c(FALSE, FALSE),
                                                     use_covariates = c(TRUE, TRUE),
                                                     ref_batch = NULL, verbose = TRUE)

plot_latent_by_batch(deepcombat_optimal$latent_logvar, input_list$input_list$batch)
#plot_latent_by_batch(resid_output$latent_mu, input_list$input_list$batch)
#plot_latent_by_batch(resid_output$combat_mu, input_list$input_list$batch)
plot_latent_by_batch(deepcombat_optimal$resids, input_list$input_list$batch)
#histogram(as.numeric(resid_model$rescaler$weight$mul(0.5)$exp()))
torch_mean(deepcombat_optimal$resids^2)

deepcombat_optimal$combat_mod <- t(input_list$covbat_output$combat.out$dat.combat)
deepcombat_optimal$covbat <- t(input_list$covbat_output$dat.covbat)
deepcombat_optimal$data <- input_list$data

optimal_list <- lapply(deepcombat_optimal, as.matrix)
#get_mse_mae(data_list[rf_interval], raw)
#umap_list <- umap_plotter(data_list[rf_interval], final_visits_covariates, n_neighbors = 15, n_epochs = 30); umap_list

manufac_results <- ml_cv_tester(optimal_list, c(6, 11), final_visits_covariates, outcome = "manufac",
                                k_fold = 10, repeats = 3, verbose = FALSE); manufac_results

anova_mat <- anova_tester(optimal_list, final_visits_covariates); anova_mat[[2]]
```

# Lambda is too big
```{r}
n_latent_dim <- 16
deepcombat_big_model <- vanilla_vae(feature_dim = 62, latent_dim = n_latent_dim,
                                    n_hidden = 3, n_batch = 1, n_covariate = 4,
                                    inject_decoder = TRUE, inject_last = FALSE, deep_inject = FALSE,
                                    rescale = FALSE, rescale_n_batch = NULL)
resid_optim <- optim_adam(deepcombat_big_model$parameters, lr = 0.01, weight_decay = 0)

trained_model <- train_nn_annealer(train_epochs = c(5, 30, 5),
                                   anneal_rate = 5,
                                   beta_weights = c(.4, 0, 0),
                                   torch_dl = adni_all_dl,
                                   torch_model = deepcombat_big_model,
                                   torch_optim = resid_optim,
                                   batch_weights = c(1, 1),
                                   pairwise_type = "none")
deepcombat_big_model <- trained_model$model

deepcombat_big_model$eval()
deepcombat_big <- deepcombat_big_model$encode_decode(adni_ct,
                                                     attr(input_list$input_list$data,
                                                          which = "scaled:center") + input_list$mean,
                                                     attr(input_list$input_list$data,
                                                          which = "scaled:scale"),
                                                     correct = c("combat", "combat"),
                                                     mean_only = c(FALSE, FALSE),
                                                     use_covariates = c(TRUE, TRUE),
                                                     ref_batch = NULL, verbose = TRUE)

plot_latent_by_batch(deepcombat_big$latent_logvar, input_list$input_list$batch)
#plot_latent_by_batch(resid_output$latent_mu, input_list$input_list$batch)
#plot_latent_by_batch(resid_output$combat_mu, input_list$input_list$batch)
plot_latent_by_batch(deepcombat_big$resids, input_list$input_list$batch)
#histogram(as.numeric(resid_model$rescaler$weight$mul(0.5)$exp()))
torch_mean(deepcombat_big$resids^2)

# deepcombat_big$combat_mod <- t(input_list$covbat_output$combat.out$dat.combat)
# deepcombat_big$covbat <- t(input_list$covbat_output$dat.covbat)
# deepcombat_big$data <- input_list$data
# 
# big_list <- lapply(deepcombat_big, as.matrix)
# #get_mse_mae(data_list[rf_interval], raw)
# #umap_list <- umap_plotter(data_list[rf_interval], final_visits_covariates, n_neighbors = 15, n_epochs = 30); umap_list
# 
# manufac_results <- ml_cv_tester(big_list, c(6, 11), final_visits_covariates, outcome = "manufac",
#                                 k_fold = 10, repeats = 1, skip_slow = TRUE); manufac_results
# 
# anova_mat <- anova_tester(big_list, final_visits_covariates); anova_mat[[2]]
```

# Lambda is too small
```{r}
n_latent_dim <- 16
deepcombat_small_model <- vanilla_vae(feature_dim = 62, latent_dim = n_latent_dim,
                                      n_hidden = 3, n_batch = 1, n_covariate = 4,
                                      inject_decoder = TRUE, inject_last = FALSE, deep_inject = FALSE,
                                      rescale = FALSE, rescale_n_batch = NULL)
resid_optim <- optim_adam(deepcombat_small_model$parameters, lr = 0.01, weight_decay = 0)

trained_model <- train_nn_annealer(train_epochs = c(5, 30, 5),
                                   anneal_rate = 5,
                                   beta_weights = c(.025, 0, 0),
                                   torch_dl = adni_all_dl,
                                   torch_model = deepcombat_small_model,
                                   torch_optim = resid_optim,
                                   batch_weights = c(1, 1),
                                   pairwise_type = "none")
deepcombat_small_model <- trained_model$model

deepcombat_small_model$eval()
deepcombat_small <- deepcombat_small_model$encode_decode(adni_ct,
                                                         attr(input_list$input_list$data,
                                                              which = "scaled:center") + input_list$mean,
                                                         attr(input_list$input_list$data,
                                                              which = "scaled:scale"),
                                                         correct = c("combat", "combat"),
                                                         mean_only = c(FALSE, FALSE),
                                                         use_covariates = c(TRUE, TRUE),
                                                         ref_batch = NULL, verbose = TRUE)

# plot_latent_by_batch(deepcombat_small$latent_logvar, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$latent_mu, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$combat_mu, input_list$input_list$batch)
# plot_latent_by_batch(deepcombat_small$resids, input_list$input_list$batch)
# #histogram(as.numeric(resid_model$rescaler$weight$mul(0.5)$exp()))
# torch_mean(deepcombat_small$resids^2)
# 
# deepcombat_small$combat_mod <- t(input_list$covbat_output$combat.out$dat.combat)
# deepcombat_small$covbat <- t(input_list$covbat_output$dat.covbat)
# deepcombat_small$data <- input_list$data
# 
# small_list <- lapply(deepcombat_small, as.matrix)
# #get_mse_mae(data_list[rf_interval], raw)
# #umap_list <- umap_plotter(data_list[rf_interval], final_visits_covariates, n_neighbors = 15, n_epochs = 30); umap_list
# 
# manufac_results <- ml_cv_tester(small_list, c(6, 11), final_visits_covariates, outcome = "manufac",
#                                 k_fold = 10, repeats = 1, skip_slow = TRUE); manufac_results
# 
# anova_mat <- anova_tester(small_list, final_visits_covariates); anova_mat[[2]]
```

# Lambda is way too big
```{r}
n_latent_dim <- 16
deepcombat_waybig_model <- vanilla_vae(feature_dim = 62, latent_dim = n_latent_dim,
                                       n_hidden = 3, n_batch = 1, n_covariate = 4,
                                       inject_decoder = TRUE, inject_last = FALSE, deep_inject = FALSE,
                                       rescale = FALSE, rescale_n_batch = NULL)
resid_optim <- optim_adam(deepcombat_waybig_model$parameters, lr = 0.01, weight_decay = 0)

trained_model <- train_nn_annealer(train_epochs = c(5, 30, 5),
                                   anneal_rate = 5,
                                   beta_weights = c(1.6, 0, 0),
                                   torch_dl = adni_all_dl,
                                   torch_model = deepcombat_waybig_model,
                                   torch_optim = resid_optim,
                                   batch_weights = c(1, 1),
                                   pairwise_type = "none")
deepcombat_waybig_model <- trained_model$model

deepcombat_waybig_model$eval()
deepcombat_waybig <- deepcombat_waybig_model$encode_decode(adni_ct,
                                                           attr(input_list$input_list$data,
                                                                which = "scaled:center") + input_list$mean,
                                                           attr(input_list$input_list$data,
                                                                which = "scaled:scale"),
                                                           correct = c("combat", "combat"),
                                                           mean_only = c(FALSE, FALSE),
                                                           use_covariates = c(TRUE, TRUE),
                                                           ref_batch = NULL, verbose = TRUE)

# plot_latent_by_batch(deepcombat_waybig$latent_logvar, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$latent_mu, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$combat_mu, input_list$input_list$batch)
# plot_latent_by_batch(deepcombat_waybig$resids, input_list$input_list$batch)
# #histogram(as.numeric(resid_model$rescaler$weight$mul(0.5)$exp()))
# torch_mean(deepcombat_waybig$resids^2)
# 
# deepcombat_waybig$combat_mod <- t(input_list$covbat_output$combat.out$dat.combat)
# deepcombat_waybig$covbat <- t(input_list$covbat_output$dat.covbat)
# deepcombat_waybig$data <- input_list$data
# 
# waybig_list <- lapply(deepcombat_waybig, as.matrix)
# #get_mse_mae(data_list[rf_interval], raw)
# #umap_list <- umap_plotter(data_list[rf_interval], final_visits_covariates, n_neighbors = 15, n_epochs = 30); umap_list
# 
# manufac_results <- ml_cv_tester(waybig_list, c(6), final_visits_covariates, outcome = "manufac",
#                                 k_fold = 10, repeats = 1, skip_slow = TRUE); manufac_results
# 
# anova_mat <- anova_tester(waybig_list, final_visits_covariates); anova_mat[[2]]
```

# Lambda is way too small
```{r}
n_latent_dim <- 16
deepcombat_waysmall_model <- vanilla_vae(feature_dim = 62, latent_dim = n_latent_dim,
                                         n_hidden = 3, n_batch = 1, n_covariate = 4,
                                         inject_decoder = TRUE, inject_last = FALSE, deep_inject = FALSE,
                                         rescale = FALSE, rescale_n_batch = NULL)
resid_optim <- optim_adam(deepcombat_waysmall_model$parameters, lr = 0.01, weight_decay = 0)

trained_model <- train_nn_annealer(train_epochs = c(5, 30, 5),
                                   anneal_rate = 5,
                                   beta_weights = c(0.00625, 0, 0),
                                   torch_dl = adni_all_dl,
                                   torch_model = deepcombat_waysmall_model,
                                   torch_optim = resid_optim,
                                   batch_weights = c(1, 1),
                                   pairwise_type = "none")
deepcombat_waysmall_model <- trained_model$model

deepcombat_waysmall_model$eval()
deepcombat_waysmall <- deepcombat_waysmall_model$encode_decode(adni_ct,
                                                               attr(input_list$input_list$data,
                                                                    which = "scaled:center") + input_list$mean,
                                                               attr(input_list$input_list$data,
                                                                    which = "scaled:scale"),
                                                               correct = c("combat", "combat"),
                                                               mean_only = c(FALSE, FALSE),
                                                               use_covariates = c(TRUE, TRUE),
                                                               ref_batch = NULL, verbose = TRUE)

# plot_latent_by_batch(deepcombat_waysmall$latent_logvar, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$latent_mu, input_list$input_list$batch)
# #plot_latent_by_batch(resid_output$combat_mu, input_list$input_list$batch)
# plot_latent_by_batch(deepcombat_waysmall$resids, input_list$input_list$batch)
# #histogram(as.numeric(resid_model$rescaler$weight$mul(0.5)$exp()))
# torch_mean(deepcombat_waysmall$resids^2)
# 
# deepcombat_waysmall$combat_mod <- t(input_list$covbat_output$combat.out$dat.combat)
# deepcombat_waysmall$covbat <- t(input_list$covbat_output$dat.covbat)
# deepcombat_waysmall$data <- input_list$data
# 
# waysmall_list <- lapply(deepcombat_waysmall, as.matrix)
# #get_mse_mae(data_list[rf_interval], raw)
# #umap_list <- umap_plotter(data_list[rf_interval], final_visits_covariates, n_neighbors = 15, n_epochs = 30); umap_list
# 
# manufac_results <- ml_cv_tester(waysmall_list, c(6), final_visits_covariates, outcome = "manufac",
#                                 k_fold = 10, repeats = 1, skip_slow = TRUE); manufac_results
# 
# anova_mat <- anova_tester(waysmall_list, final_visits_covariates); anova_mat[[2]]
```

```{r}
deepcombat_harmonized <- list(optimal = deepcombat_optimal$combat_restyle,
                              small = deepcombat_small$combat_restyle,
                              waysmall = deepcombat_waysmall$combat_restyle,
                              big = deepcombat_big$combat_restyle,
                              waybig = deepcombat_waybig$combat_restyle) %>% 
  lapply(as.matrix) %>% lapply(as.data.frame)
deepcombat_latentvars <- list(optimal = deepcombat_optimal$latent_logvar,
                              small = deepcombat_small$latent_logvar,
                              waysmall = deepcombat_waysmall$latent_logvar,
                              big = deepcombat_big$latent_logvar,
                              waybig = deepcombat_waybig$latent_logvar) %>% 
  lapply(as.matrix) %>% lapply(as.data.frame)
deepcombat_latentmeans <- list(optimal = deepcombat_optimal$latent_mu,
                               small = deepcombat_small$latent_mu,
                               waysmall = deepcombat_waysmall$latent_mu,
                               big = deepcombat_big$latent_mu,
                               waybig = deepcombat_waybig$latent_mu) %>% 
  lapply(as.matrix) %>% lapply(as.data.frame)
```

