---
title: "scvi_analysis"
output: html_document
---

```{r}
source("~/Documents/nnbatch/code/load_packages.R")
```

## Reading in data
```{r}
resids_matrix <- as.matrix(resid_output$resids)
rescale_factor <- matrix(colSds(resids_matrix[covariates$manufac == "False", ]) / colSds(resids_matrix[covariates$manufac == "True", ]),
                            ncol = 62, byrow = TRUE)
resids_matrix[covariates$manufac == "True", ] <- resids_matrix[covariates$manufac == "True", ] * rep(1, dim(resids_matrix[covariates$manufac == "True", ])[1]) %*% rescale_factor

covbat_resids <- covbat(t(as.matrix(resid_output$resids)), bat = batch, mod = cbind(cov_mod))#$dat.covbat %>% t()

data_list <- list(#raw = raw,
                  #cov = cov,
                  combat = combat,
                  covbat = covbat,
                  vae_resids = vae_output$resids,
                  vae_restyleresids = torch_tensor(raw_demean) + vae_output$resids_restyle,
                  vae_combat = torch_tensor(raw_demean) + vae_output$restyle + resid_output$combat_restyle,
                  vae_combat2 = torch_tensor(raw_demean) + vae_output$restyle + resid_output$combat + torch_tensor(resids_matrix),
                  vae_combat3 = torch_tensor(raw_demean) + vae_output$restyle + resid_output$combat + torch_tensor(t(covbat_resids$combat.out$dat.combat)),
                  vae_covbat = torch_tensor(raw_demean) + vae_output$restyle + resid_output$combat + torch_tensor(t(covbat_resids$dat.covbat)),
                  #vae_recon = vae_output$recon,
                  #vae_restyle = torch_tensor(raw_demean) + vae_output$restyle,
                  #vae_corrected_resids = tx_resid_output$recon,
                  #vae_corrected_restyle = tx_resid_output$combat_restyle,
                  #vae_corrected_rr = vae_output$combat + resid_output$combat_restyle,
                  #vae_corrected2_rr = torch_tensor(raw_demean) + vae_output$restyle + tx_resid_output$restyle,
                  #vae_corrected3_rr = torch_tensor(raw_demean) + vae_output$restyle + torch_tensor(covbat_resids),
                  #vae_corrected4_rr = vae_output$restyle + vae_output$resid - tx_resid_output$recon + tx_resid_output$combat_restyle,
                  vae_mu = vae_output$latent_mu,
                  resid_mu = vae_output$latent_mu
                  #vae_combat_mu = vae_output$combat_restyle
                  #resid_mu = tx_resid_output$latent_mu,
                  #resid_mu_combat = tx_resid_output$combat
                  )
data_list <- lapply(data_list, as.matrix)

## MSE from raw
get_mse_mae(data_list[1:(length(data_list) - 1)], raw)

## ANOVA test for scanner/biologic effects
#anova_mat <- anova_tester(data_list, covariates); anova_mat[[2]]
#                           AGE      SEXM DIAGNOSISCN DIAGNOSISLMCI RandomRandom_2 manufacTrue
# raw                    287.800     9.791     250.900        92.570         0.5629   1.325e+02
# combat                 287.800     9.791     250.900        92.570         0.5629   1.325e+02
# covbat                 287.500     9.762     250.300        92.760         0.5779   7.266e-03

## Plot UMAPs of data in thickness-space
#umap_list <- umap_plotter(data_list, covariates, n_neighbors = 15, n_epochs = 30); umap_list

## Random forest test for scanner/biologic effects
rf_interval <- 1:length(data_list)
rf_list <- rf_splitter(data_list[rf_interval], covariates, seed = 10)
rf_error_df <- rf_tester(rf_list$train_list, rf_list$train_covariates, rf_list$test_list, rf_list$test_covariates, interval = rf_interval); rf_error_df
#                               AGE       SEX  DIAGNOSIS    Random   manufac
# raw                      42.42772 0.3701431 0.08433735 0.4130879 0.1492843
# covariate_baseline       21.94670 0.0000000 0.00000000 0.4683027 0.4683027
# combat                   41.91287 0.3926380 0.07692308 0.4560327 0.3537832
# covbat                   40.58314 0.3844581 0.09210526 0.4683027 0.3824131
# pred_resids              44.55263 0.3926380 0.12903226 0.4233129 0.3047034
# pred_restyle             0.663932 0.0000000 0.00000000 0.5071575 0.4969325
# lin_resids               39.33793 0.09202454 0.1393939 0.3844581 0.0756646
# lin_restyle              0.037666 0.00000000 0.0000000 0.5112474 0.5051125
```

## Silhouette test for whether longitudinal scans are clustered together
```{r}
mean_sub_sil_scores <- subject_silhouette_tester(data_list, covariates); mean_sub_sil_scores
```

## Plots of overall, Siemens, GE/Phillips, and Difference covariance matrices
```{r}
cov_list <- cov_generator(data_list, covariates)
cov_plot_list <- cov_plotter(cov_list)

lapply(cov_list, function(cov_mat) {
  norm(cov_mat[[4]], type = "F")
})
```

## Plots of pre/post correction covariance matrices between subjects
```{r}
max_cor_matrix_list <- get_pre_post(data_list, similarity_type = "correlation", covariates, n_max = 10)
post_post_cor_matrix <- get_pre_post(list(data_list[[2]], data_list[[2]]), similarity_type = "manhattan", covariates = covariates, n_max = 10)
latent_cor_matrix <- get_pre_post(list(scvi_latent, scvi_latent), similarity_type = "euclidean", covariates = covariates, n_max = 10)

pre_post_analyzer(max_cor_matrix_list, covariates)[[4]] %>% colSums()
pre_post_analyzer(post_post_cor_matrix, covariates)[[1]] %>% colSums()
```

```{r}
resid_df <- as.matrix(vae_output$resids) %>% as.data.frame() %>% 
  cbind(manufac = covariates$manufac) %>% cbind(strength = covariates$strength) %>% cbind(true_man = covariates$Manufacturer) %>% 
  cbind(sex = covariates$SEX) %>% cbind(diag = covariates$DIAGNOSIS)
ggplot(resid_df) + geom_density(aes(V20, fill =  manufac), alpha = .5)
ggplot(resid_df %>% filter(manufac == "True")) + geom_density(aes(V2, fill = strength), alpha = .5)
ggplot(resid_df %>% filter(manufac == "False")) + geom_density(aes(V10, fill = strength), alpha = .5)
```

```{r}
raw_resids_matrix <- data_list$combat_restyle - input_list$mean

#colMeans(raw_resids_matrix[covariates$manufac == "False", ])
#colMeans(raw_resids_matrix[covariates$manufac == "True", ])

resids_matrix_0 <- raw_resids_matrix[covariates$manufac == "False", ]
resids_matrix_1 <- raw_resids_matrix[covariates$manufac == "True", ]

cov_ratio <- cov(resids_matrix_1) / cov(resids_matrix_0)
cor_ratio <- cor(resids_matrix_1) / cor(resids_matrix_0)

mean(cov_ratio > 1)
mean(cor_ratio > 1)

norm(cov(resids_matrix_1) - cov(resids_matrix_0), type = "F")
```

```{r}
mod_lm <- lm()
```

