---
title: "revisions_analysis"
output: html_document
---

# Load libraries
```{r}
library(tidyverse)
library(here)

library(DeepComBat)
library(neuroCombat)
library(CovBat)

library(GGally)
library(ggfortify)
library(ggpubr)

library(umap)
library(caret)
library(matrixStats)
library(twosamples)
library(kBET)

source("/home/fengling/Documents/nnbatch/code/eval_utils_revisions.R")
source("/home/fengling/Documents/nnbatch/code/revisions/combat_from_train.R")
```

# Preprocessing
```{r}
source("./code/load_packages.R")
all_cov <- read.csv("./data/covariates.csv")
all_cov$SEX <- as.factor(all_cov$SEX)
all_cov$DIAGNOSIS <- as.factor(all_cov$DIAGNOSIS)
all_cov$Random <- as.factor(all_cov$Random)
all_cov$manufac <- as.factor(all_cov$manufac)
all_cov$Manufacturer <- as.factor(all_cov$Manufacturer)

unique_cov <- all_cov %>% 
  mutate(X.1 = X.1 + 1) %>% 
  group_by(subid) %>% 
  filter(VISIT == max(VISIT)) %>% 
  as.data.frame()
rm(all_cov)

raw <- as.matrix(read.csv("./data/raw.csv", header = F))
unique_raw <- raw[unique_cov$X.1, ]
rm(raw)

cov <- model.matrix(~ SEX + DIAGNOSIS + AGE, unique_cov)[, -1]
batch <- as.matrix(model.matrix(~ Manufacturer, unique_cov)[, -1])

files_list <- lapply(list.files("./data/for_paper", 
                                full.names = TRUE, pattern = "*.csv"), 
                     read_csv)

combat_harmonized <- neuroCombat(dat = t(unique_raw), 
                                 batch = unique_cov$Manufacturer, mod = cov)$dat.combat %>% t()
covbat_harmonized <- covbat(dat = t(unique_raw), 
                            bat = unique_cov$Manufacturer, mod = cov)$dat.covbat %>% t()

setup <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, ~ Manufacturer, unique_raw, unique_cov)
train <- deepcombat_trainer(setup, verbose = TRUE)
harmonized <- deepcombat_harmonize(setup, train, plot_logvars = TRUE)
```

# Save harmonized data
```{r}
write.csv(combat_harmonized, "./data/revisions/internal_harmonization/combat.csv", row.names = F)
write.csv(covbat_harmonized, "./data/revisions/internal_harmonization/covbat.csv", row.names = F)
write.csv(harmonized$harmonized, "./data/revisions/deepcombat_01.csv", row.names = F)
```

# Trying different lambdas
```{r}
setup_00625 <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, ~ Manufacturer, 
                                unique_raw, unique_cov)
train_00625 <- deepcombat_trainer(setup_00625, lambda = 0.00625, verbose = TRUE)
harmonized_00625 <- deepcombat_harmonize(setup_00625, train_00625, plot_logvars = TRUE)

setup_025 <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, ~ Manufacturer, 
                                unique_raw, unique_cov)
train_025 <- deepcombat_trainer(setup_025, lambda = 0.025, verbose = TRUE)
harmonized_025 <- deepcombat_harmonize(setup_025, train_025, plot_logvars = TRUE)

setup_4 <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, ~ Manufacturer, 
                                unique_raw, unique_cov)
train_4 <- deepcombat_trainer(setup_4, lambda = 0.4, verbose = TRUE)
harmonized_4 <- deepcombat_harmonize(setup_4, train_4, plot_logvars = TRUE)

setup_16 <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, ~ Manufacturer, 
                                unique_raw, unique_cov)
train_16 <- deepcombat_trainer(setup_16, lambda = 1.6, verbose = TRUE)
harmonized_16 <- deepcombat_harmonize(setup_16, train_16, plot_logvars = TRUE)
```

```{r}
write.csv(harmonized_00625$harmonized, "./data/revisions/internal_lambdas/deepcombat_00625.csv", row.names = F)
write.csv(harmonized_025$harmonized, "./data/revisions/internal_lambdas/deepcombat_025.csv", row.names = F)
write.csv(harmonized_4$harmonized, "./data/revisions/internal_lambdas/deepcombat_4.csv", row.names = F)
write.csv(harmonized_16$harmonized, "./data/revisions/internal_lambdas/deepcombat_16.csv", row.names = F)
```

<!-- # Statistical testing -->
<!-- ```{r} -->
<!-- data_list <- list(raw = final_visits_raw, combat = combat_harmonized,  -->
<!--                   covbat = covbat_harmonized, dc = harmonized$harmonized, -->
<!--                   cvae = files_list[[6]], gcvae = files_list[[7]]) -->
<!-- stats_test <- stats_tester(data_list[1:4], final_visits_covariates) -->
<!-- stats_test[[1]] -->

<!-- kbet_list <- lapply(data_list, function(df) { -->
<!--   kbet_obj <- kBET(df, batch = final_visits_covariates$manufac) -->
<!--   return(kbet_obj) -->
<!-- }) -->

<!-- kbet_df <- lapply(kbet_list, function(kbet_out) {kbet_out$summary[1, ]}) %>%  -->
<!--   do.call(rbind, .) %>%  -->
<!--   rename(`Expected kBET` = kBET.expected, `Observed kBET` = kBET.observed, `p-value` = kBET.signif) %>% round(digits = 3) -->
<!-- ``` -->

<!-- # ML testing -->
<!-- ```{r} -->
<!-- feature_plotter(data_list, final_visits_covariates, names(data_list)) -->
<!-- pca_plotter(data_list, final_visits_covariates, names(data_list)) -->
<!-- umap_plotter(data_list, final_visits_covariates, names(data_list)) -->

<!-- manufac_ml <- ml_cv_tester(data_list, 1:4, final_visits_covariates, -->
<!--                            outcome = "manufac", repeats = 20) -->

<!-- ml_names <- c("RF", "SVM (Radial)", "KNN", "QDA", "XGBoost") -->
<!-- manufac_methods <- vector("list", length(data_list[1:4])) -->
<!-- n_per_list <- nrow(manufac_ml) / length(data_list[1:4]) -->
<!-- for (i in 1:length(data_list[1:4])) { -->
<!--   start_ind <- ((i - 1) * n_per_list + 1) -->
<!--   end_ind <- i * n_per_list -->
<!--   manufac_methods[[i]] <- manufac_ml[start_ind:end_ind, ] -->
<!-- } -->

<!-- manufac_methods_df <- bind_rows(manufac_ml) %>% -->
<!--   mutate(algorithm = as.factor(rep(ml_names, length(manufac_methods))), -->
<!--          algorithm_releveled = fct_relevel(algorithm, -->
<!--                                            "SVM (Radial)", "QDA", -->
<!--                                            "KNN", "RF", "XGBoost"), -->
<!--          harm_method = as.factor(rep(c("Raw", "ComBat", "CovBat", -->
<!--                                        "DeepComBat"), -->
<!--                                      each = length(ml_names))), -->
<!--          harm_method_releveled = fct_relevel(harm_method, -->
<!--                                              "Raw", "ComBat", "CovBat", -->
<!--                                              "DeepComBat")) -->

<!-- manufac_methods_df <- manufac_methods_df %>% -->
<!--   group_by(algorithm_releveled, harm_method_releveled) %>% -->
<!--   summarize(ROC = mean(validation_roc), -->
<!--             ROCSD = sd(validation_roc) / 10 * 1.984) -->

<!-- my_colors <- c("#1F78B4", "#B2DF8A", "#33A02C", "#CAB2D6") -->
<!-- manufac_plot <- ggplot(manufac_methods_df, aes(x = algorithm_releveled, y = Accuracy, -->
<!--                                                fill = harm_method_releveled)) + -->
<!--   geom_bar(stat = "identity", position = position_dodge(.9)) + -->
<!--   geom_hline(yintercept = 0.33, color = "red", linetype = "dashed") + -->
<!--   geom_errorbar(aes(ymin = Accuracy - 1.984 * AccuracySD / sqrt(200), ymax = Accuracy + 1.984 * AccuracySD / sqrt(200)), -->
<!--                 position = position_dodge(.9)) + -->
<!--   scale_fill_manual(values = my_colors, name = "Methods") + -->
<!--   coord_cartesian(ylim = c(0.33, 1)) + -->
<!--   ggtitle("Batch") + -->
<!--   xlab("Machine Learning Algorithm") + -->
<!--   ylab("AUROC") + -->
<!--   theme_minimal() + -->
<!--   theme(panel.grid.major.x = element_blank(), -->
<!--         panel.grid.minor.x = element_blank(), -->
<!--         plot.title = element_text(hjust = 0.5)); manufac_plot -->
<!-- ``` -->

# Validation split/test
```{r}
cv_vector <- sample(rep(1:10, nrow(final_visits_raw))[1:nrow(final_visits_raw)])

cv_harmonization <- function(data, covariates, cv_vector, cv_id) {
  train_inds <- cv_vector != cv_id
  val_inds <- cv_vector == cv_id
  cov <- model.matrix(~ SEX + DIAGNOSIS + AGE, covariates)[, -1]
  
  if (is.null(cv_id)) {
    message("Using whole dataset as training with no validation")
    train_inds <- rep(TRUE, nrow(data))
  }
  
  combat_train <- neuroCombat(dat = t(data[train_inds, ]), 
                              batch = covariates$Manufacturer[train_inds], 
                              mod = cov[train_inds, ])
  covbat_train <- covbat(dat = t(data[train_inds, ]), 
                         bat = covariates$Manufacturer[train_inds], 
                         mod = cov[train_inds, ])
  setup_train <- deepcombat_setup(~ AGE + SEX + DIAGNOSIS, 
                                  ~ Manufacturer, 
                                  data[train_inds, ], 
                                  covariates[train_inds, ],
                                  cvae_settings = list(n_hidden = 2, vae_dim = c(62, 30, 16, 8)),
                                  use_default_optim = FALSE)
  trainer_train <- deepcombat_trainer(setup_train, verbose = TRUE, optimizer = optim_adamw(setup_train$cvae$parameters, lr = 0.01))
  harmonized_train <- deepcombat_harmonize(setup_train, trainer_train)
  
  message("Performing validation harmonization")
  if (!is.null(cv_id)) {
    combat_val <- combat_from_train(dat = t(data[val_inds, ]), 
                                    batch = covariates$Manufacturer[val_inds], 
                                    mod = cov[val_inds, ],
                                    estimates = combat_train$estimates)
    covbat_val <- covbat_from_train(dat = t(data[val_inds, ]), 
                                    batch = covariates$Manufacturer[val_inds], 
                                    mod = cov[val_inds, ],
                                    covbat_train = covbat_train)
    setup_val <- deepcombat_setup_from_train(setup_train, 
                                             ~ AGE + SEX + DIAGNOSIS, 
                                             ~ Manufacturer, 
                                             data[val_inds, ], 
                                             covariates[val_inds, ])
    message("Harmonizing")
    harmonized_val <- deepcombat_harmonize(setup_val, trainer_train, harmonized_train, verbose = TRUE)
    return(list(combat_train = t(combat_train$dat.combat),
                combat_val = t(combat_val$dat.combat),
                covbat_train = t(covbat_train$dat.covbat),
                covbat_val = t(covbat_val$dat.covbat),
                dc_train = harmonized_train$harmonized,
                dc_val = harmonized_val$harmonized))
  } else {
    return(list(combat_train = t(combat_train$dat.combat),
                covbat_train = t(covbat_train$dat.covbat),
                dc_train = harmonized_train$harmonized))
  }
}

cv_harm_output <- lapply(1:10, function(cv_id) {
  cv_harmonization(final_visits_raw, final_visits_covariates, cv_vector, cv_id)
})

combat_val <- matrix(nrow = nrow(final_visits_raw), ncol = ncol(final_visits_raw))
covbat_val <- matrix(nrow = nrow(final_visits_raw), ncol = ncol(final_visits_raw))
dc_val <- matrix(nrow = nrow(final_visits_raw), ncol = ncol(final_visits_raw))
for (i in 1:10) {
  combat_val[cv_vector == i, ] <- cv_harm_output[[i]]$combat_val
  covbat_val[cv_vector == i, ] <- cv_harm_output[[i]]$covbat_val
  dc_val[cv_vector == i, ] <- cv_harm_output[[i]]$dc_val
}

silver_standard <- cv_harmonization(final_visits_raw, final_visits_covariates, cv_vector, NULL)
# (silver_standard$combat_train - combat_val)^2 %>% mean
# (silver_standard$covbat_train - covbat_val)^2 %>% mean
# (silver_standard$dc_train - dc_val)^2 %>% mean
# 
# abs(silver_standard$combat_train - combat_val) %>% mean
# abs(silver_standard$covbat_train - covbat_val) %>% mean
# abs(silver_standard$dc_train - dc_val) %>% mean
# 
# cor(as.vector(silver_standard$combat_train), as.vector(combat_val))
# cor(as.vector(silver_standard$covbat_train), as.vector(covbat_val))
# cor(as.vector(silver_standard$dc_train), as.vector(dc_val))
```

```{r}
write.csv(combat_val, "./data/revisions/combat_val_0121.csv")
write.csv(covbat_val, "./data/revisions/covbat_val_0121.csv")
write.csv(dc_val, "./data/revisions/deepcombat_01_val_0121.csv")
```

# CV Statistical testing
```{r}
cv_data_list <- list(raw = final_visits_raw, combat = combat_val, 
                     covbat = covbat_val, dc = dc_val, 
                     dcreg = silver_standard$dc_train,
                     dcmle = harmonized$harmonized)
stats_test <- stats_tester(cv_data_list[1:6], final_visits_covariates)
stats_test[[1]]

kbet_list <- lapply(cv_data_list, function(df) {
  kbet_obj <- kBET(df, batch = final_visits_covariates$Manufacturer)
  return(kbet_obj)
})

kbet_df <- lapply(kbet_list, function(kbet_out) {kbet_out$summary[1, ]}) %>% 
  do.call(rbind, .) %>% 
  rename(`Expected kBET` = kBET.expected, `Observed kBET` = kBET.observed, `p-value` = kBET.signif) %>% round(digits = 3)
kbet_df
```

# CV ML testing
```{r}
feature_plotter(cv_data_list, final_visits_covariates, names(cv_data_list))
pca_plotter(cv_data_list, final_visits_covariates, names(cv_data_list))
umap_plotter(cv_data_list, final_visits_covariates, names(cv_data_list))

cv_manufac_ml <- ml_cv_tester(cv_data_list, 1:5, final_visits_covariates, 
                              outcome = "Manufacturer", repeats = 20)

ml_names <- c("RF", "SVM (Radial)", "KNN", "QDA", "XGBoost")
cv_manufac_methods <- vector("list", length(cv_data_list[1:5]))
n_per_list <- nrow(cv_manufac_ml) / length(cv_data_list[1:5])
for (i in 1:length(cv_data_list[1:5])) {
  start_ind <- ((i - 1) * n_per_list + 1)
  end_ind <- i * n_per_list
  cv_manufac_methods[[i]] <- cv_manufac_ml[start_ind:end_ind, ]
}

cv_manufac_methods_df <- bind_rows(cv_manufac_ml) %>% 
  mutate(algorithm = as.factor(rep(ml_names, length(cv_manufac_methods))),
         algorithm_releveled = fct_relevel(algorithm, 
                                           "SVM (Radial)", "QDA", 
                                           "KNN", "RF", "XGBoost"),
         harm_method = as.factor(rep(c("Raw", "ComBat", "CovBat", 
                                       "DeepComBatVal", "DeepComBatReg"),
                                     each = length(ml_names))),
         harm_method_releveled = fct_relevel(harm_method, 
                                             "Raw", "ComBat", "CovBat", 
                                             "DeepComBatVal", "DeepComBatReg"))

# cv_manufac_methods_df <- cv_manufac_methods_df %>% 
#   group_by(algorithm_releveled, harm_method_releveled) %>% 
#   summarize(ROC = mean(validation_roc),
#             ROCSD = sd(validation_roc) / 10 * 1.984)

my_colors <- c("#1F78B4", "#B2DF8A", "#33A02C", "#CAB2D6")
my_colors <- c("#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#CAB2D6")
cv_manufac_plot <- ggplot(rbind(manufac_methods_df, cv_manufac_methods_df), aes(x = algorithm_releveled, y = Accuracy, 
                                                                                fill = harm_method_releveled)) + 
  geom_bar(stat = "identity", position = position_dodge(.9)) + 
  geom_hline(yintercept = 0.33, color = "red", linetype = "dashed") + 
  geom_errorbar(aes(ymin = Accuracy - 1.984 * AccuracySD / sqrt(200), ymax = Accuracy + 1.984 * AccuracySD / sqrt(200)), 
                position = position_dodge(.9)) + 
  scale_fill_manual(values = my_colors, name = "Methods") + 
  coord_cartesian(ylim = c(0.33, 1)) +
  ggtitle("Batch") +
  xlab("Machine Learning Algorithm") +
  ylab("Accuracy") + 
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title = element_text(hjust = 0.5)); cv_manufac_plot
```